# Generated by Django 5.2.3 on 2025-07-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
